'use strict';

/**
 * Canonical catalog for the PlayBound mini-game platform.
 * Tags are ledger keys for addScore / faction challenges.
 */

const CATEGORIES = new Set([
    'trivia',
    'dice',
    'cards',
    'reaction',
    'guess',
    'social',
    'puzzle',
    'elimination',
]);

/** @type {Record<string, object>} */
const GAME_REGISTRY = {
    risk_roll: {
        id: 'risk_roll',
        displayName: 'Risk Roll',
        tag: 'risk_roll',
        category: 'dice',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 8,
        defaultCasualRewards: { win: 12, participate: 3, cleanWinBonus: 4 },
        warScoringEligible: true,
        rotationWeight: 1,
        difficultyProfile: 'medium',
        estimatedDurationSec: 150,
        playerCountMode: 'solo_or_small',
        supportsDuel: true,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: {
            bustOn: 1,
            maxRounds: 6,
            sessionCapFaction: 40,
            comboBonusRanked: false,
        },
    },
    target_21: {
        id: 'target_21',
        displayName: 'Target 21',
        tag: 'target_21',
        category: 'dice',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 8,
        defaultCasualRewards: { win: 14, exact21Bonus: 8, bust: 1 },
        warScoringEligible: true,
        rotationWeight: 1.1,
        difficultyProfile: 'easy',
        estimatedDurationSec: 90,
        playerCountMode: 'solo',
        supportsDuel: true,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { dieSides: 6, sessionCapFaction: 35, bestRunOnlyRanked: true, matchRounds: 3 },
    },
    dice_duel: {
        id: 'dice_duel',
        displayName: 'Dice Duel',
        tag: 'dice_duel',
        category: 'dice',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 10,
        defaultCasualRewards: { win: 12, comboBonusCasual: 5 },
        warScoringEligible: true,
        rotationWeight: 1,
        difficultyProfile: 'easy',
        estimatedDurationSec: 120,
        playerCountMode: 'duel',
        supportsDuel: true,
        supportsRoyale: false,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { comboBonusRanked: false, sessionCapFaction: 30, matchRounds: 3 },
    },
    king_of_the_hill: {
        id: 'king_of_the_hill',
        displayName: 'King of the Hill Roll',
        tag: 'king_of_the_hill',
        category: 'dice',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 9,
        defaultCasualRewards: { win: 14, dethroneBonus: 3, participate: 2 },
        warScoringEligible: true,
        rotationWeight: 0.95,
        difficultyProfile: 'medium',
        estimatedDurationSec: 150,
        playerCountMode: 'small_group',
        supportsDuel: true,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { rounds: 4, sessionCapFaction: 36 },
    },
    high_card_blitz: {
        id: 'high_card_blitz',
        displayName: 'High Card Blitz',
        tag: 'high_card_blitz',
        category: 'cards',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 7,
        defaultCasualRewards: { win: 11, doubleDownBonus: 6, doubleDownFail: -2 },
        warScoringEligible: true,
        rotationWeight: 1,
        difficultyProfile: 'easy',
        estimatedDurationSec: 120,
        playerCountMode: 'solo',
        supportsDuel: true,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { doubleDownRanked: false, sessionCapFaction: 25, matchRounds: 3 },
    },
    push_luck_deck: {
        id: 'push_luck_deck',
        displayName: 'Push Your Luck Deck',
        tag: 'push_luck_deck',
        category: 'cards',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 8,
        defaultCasualRewards: { win: 13, survivalBonus: 4 },
        warScoringEligible: true,
        rotationWeight: 0.9,
        difficultyProfile: 'medium',
        estimatedDurationSec: 180,
        playerCountMode: 'solo',
        supportsDuel: true,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { rankedBankCap: 18, sessionCapFaction: 32, matchRounds: 3 },
    },
    combo_builder: {
        id: 'combo_builder',
        displayName: 'Combo Builder',
        tag: 'combo_builder',
        category: 'cards',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 9,
        defaultCasualRewards: { win: 15, tierBonus: { 1: 2, 2: 4, 3: 6, 4: 8, 5: 10 } },
        warScoringEligible: true,
        rotationWeight: 0.85,
        difficultyProfile: 'medium',
        estimatedDurationSec: 120,
        playerCountMode: 'solo',
        supportsDuel: true,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { draws: 5, sessionCapFaction: 40, matchRounds: 3 },
    },
    five_card_draw: {
        id: 'five_card_draw',
        displayName: 'Five Card Draw',
        tag: 'five_card_draw',
        category: 'cards',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 5,
        defaultCasualRewards: { participate: 2 },
        warScoringEligible: true,
        rotationWeight: 0.9,
        difficultyProfile: 'medium',
        estimatedDurationSec: 60,
        playerCountMode: 'solo',
        supportsDuel: true,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { sessionCapFaction: 30, matchRounds: 3 },
    },
    reaction_rush: {
        id: 'reaction_rush',
        displayName: 'Reaction Rush',
        tag: 'reaction_rush',
        category: 'reaction',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 6,
        defaultCasualRewards: { first: 12, second: 5, third: 2 },
        warScoringEligible: true,
        rotationWeight: 1.2,
        difficultyProfile: 'easy',
        estimatedDurationSec: 90,
        playerCountMode: 'open_channel',
        supportsDuel: true,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { rankedWinsPerUserCap: 8, sessionCapFaction: 24, matchRounds: 3 },
    },
    closest_guess: {
        id: 'closest_guess',
        displayName: 'Closest Guess Wins',
        tag: 'closest_guess',
        category: 'guess',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 7,
        defaultCasualRewards: { win: 12, exactHitBonus: 10 },
        warScoringEligible: true,
        rotationWeight: 1,
        difficultyProfile: 'easy',
        estimatedDurationSec: 90,
        playerCountMode: 'open_channel',
        supportsDuel: true,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { sessionCapFaction: 28, matchRounds: 1 },
    },
    last_man_standing: {
        id: 'last_man_standing',
        displayName: 'Last Man Standing',
        tag: 'last_man_standing',
        category: 'elimination',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 12,
        defaultCasualRewards: { win: 18, surviveRound: 2 },
        warScoringEligible: true,
        rotationWeight: 0.8,
        difficultyProfile: 'hard',
        estimatedDurationSec: 180,
        playerCountMode: 'solo_vs_bots',
        supportsDuel: false,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { placementTable: { 1: 12, 2: 6, 3: 3 }, sessionCapFaction: 36 },
    },
    pattern_memory: {
        id: 'pattern_memory',
        displayName: 'Pattern Memory',
        tag: 'pattern_memory',
        category: 'puzzle',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 8,
        defaultCasualRewards: { perRound: 3, win: 10 },
        warScoringEligible: true,
        rotationWeight: 0.9,
        difficultyProfile: 'medium',
        estimatedDurationSec: 120,
        playerCountMode: 'solo',
        supportsDuel: true,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { maxRounds: 4, factionPointsPerRound: 4, sessionCapFaction: 32 },
    },
    logic_grid_mini: {
        id: 'logic_grid_mini',
        displayName: 'Zebra Puzzle Mini',
        tag: 'logic_grid_mini',
        category: 'puzzle',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 8,
        defaultCasualRewards: { solve: 14, speedBonus: 4 },
        warScoringEligible: true,
        rotationWeight: 0.85,
        difficultyProfile: 'hard',
        estimatedDurationSec: 60,
        playerCountMode: 'solo',
        supportsDuel: true,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { sessionCapFaction: 24, matchRounds: 3 },
    },
    multi_step_trivia: {
        id: 'multi_step_trivia',
        displayName: 'Multi-Step Trivia',
        tag: 'multi_step_trivia',
        category: 'trivia',
        enabled: true,
        rankedEligible: true,
        defaultBasePoints: 10,
        defaultCasualRewards: { perStep: 3, fullChainBonus: 8 },
        warScoringEligible: true,
        rotationWeight: 1,
        difficultyProfile: 'medium',
        estimatedDurationSec: 120,
        playerCountMode: 'solo',
        supportsDuel: true,
        supportsRoyale: true,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { steps: 5, tierPoints: [4, 6, 7, 8, 10], sessionCapFaction: 35 },
    },
    lie_detector: {
        id: 'lie_detector',
        displayName: 'Lie Detector',
        tag: 'lie_detector',
        category: 'social',
        enabled: true,
        rankedEligible: false,
        defaultBasePoints: 6,
        defaultCasualRewards: { detect: 10, fool: 6 },
        warScoringEligible: false,
        rotationWeight: 0.7,
        difficultyProfile: 'medium',
        estimatedDurationSec: 120,
        playerCountMode: 'solo',
        supportsDuel: false,
        supportsRoyale: false,
        supportsTeamPlay: false,
        featuredBonusEligible: true,
        balancingConfig: { sessionCapFaction: 20 },
    },
    vote_the_winner: {
        id: 'vote_the_winner',
        displayName: 'Vote the Winner',
        tag: 'vote_the_winner',
        category: 'social',
        enabled: true,
        rankedEligible: false,
        defaultBasePoints: 5,
        defaultCasualRewards: { win: 12, vote: 2 },
        warScoringEligible: false,
        rotationWeight: 0.65,
        difficultyProfile: 'easy',
        estimatedDurationSec: 180,
        playerCountMode: 'open_channel',
        supportsDuel: false,
        supportsRoyale: false,
        supportsTeamPlay: true,
        featuredBonusEligible: true,
        balancingConfig: {},
    },
    sabotage_mode: {
        id: 'sabotage_mode',
        displayName: 'Sabotage Mode',
        tag: 'sabotage_mode',
        category: 'social',
        enabled: true,
        rankedEligible: false,
        defaultBasePoints: 7,
        defaultCasualRewards: { teamWin: 10, sabotageSuccess: 8 },
        warScoringEligible: false,
        rotationWeight: 0.6,
        difficultyProfile: 'hard',
        estimatedDurationSec: 240,
        playerCountMode: 'solo_story',
        supportsDuel: false,
        supportsRoyale: false,
        supportsTeamPlay: true,
        featuredBonusEligible: false,
        balancingConfig: {},
    },
};

const PLATFORM_GAME_TAGS = Object.keys(GAME_REGISTRY);

function getGameDefinition(tag) {
    return GAME_REGISTRY[String(tag || '').toLowerCase()] || null;
}

function listGames() {
    return PLATFORM_GAME_TAGS.map((t) => ({ ...GAME_REGISTRY[t], balancingConfig: { ...GAME_REGISTRY[t].balancingConfig } }));
}

function mergeGameWithOverrides(base, overrides) {
    if (!overrides || typeof overrides !== 'object') return { ...base, balancingConfig: { ...base.balancingConfig } };
    const b = { ...base, balancingConfig: { ...base.balancingConfig, ...(overrides.balancingConfig || {}) } };
    for (const k of [
        'enabled',
        'rankedEligible',
        'rotationWeight',
        'defaultBasePoints',
        'featuredBonusEligible',
        'warScoringEligible',
    ]) {
        if (overrides[k] !== undefined) b[k] = overrides[k];
    }
    if (overrides.defaultCasualRewards) b.defaultCasualRewards = { ...base.defaultCasualRewards, ...overrides.defaultCasualRewards };
    return b;
}

module.exports = {
    CATEGORIES,
    GAME_REGISTRY,
    PLATFORM_GAME_TAGS,
    getGameDefinition,
    listGames,
    mergeGameWithOverrides,
};
