require('dotenv').config();
const mongoose = require('mongoose');
const { Phrase, MovieQuote } = require('./models');

// Format: "PHRASE|Clue"
const rawPhrases = [
    // Idioms & Sayings
    "A BLESSING IN DISGUISE|A good thing that seemed bad at first",
    "A DIME A DOZEN|Something common and easy to find",
    "BEAT AROUND THE BUSH|Avoid saying what you mean",
    "BETTER LATE THAN NEVER|Arriving late is better than not coming",
    "BITE THE BULLET|To endure a painful experience",
    "BREAK A LEG|Good luck",
    "CALL IT A DAY|Stop working on something",
    "CUT SOMEBODY SOME SLACK|Don't be so critical",
    "CUTTING CORNERS|Doing something poorly to save time or money",
    "EASY DOES IT|Slow down",
    "GET OUT OF HAND|Get out of control",
    "GET SOMETHING OUT OF YOUR SYSTEM|Do the thing you've been wanting to do so you can move on",
    "GET YOUR ACT TOGETHER|Work better or leave",
    "GIVE SOMEONE THE BENEFIT OF THE DOUBT|Trust what someone says",
    "GO BACK TO THE DRAWING BOARD|Start over",
    "HANG IN THERE|Don't give up",
    "HIT THE SACK|Go to sleep",
    "IT IS NOT ROCKET SCIENCE|It's not complicated",
    "LET SOMEONE OFF THE HOOK|To not hold someone responsible",
    "MAKE A LONG STORY SHORT|Tell something briefly",
    "MISS THE BOAT|It's too late",
    "NO PAIN NO GAIN|You have to work for what you want",
    "ON THE BALL|Doing a good job",
    "PULL SOMEONES LEG|To joke with someone",
    "PULL YOURSELF TOGETHER|Calm down",
    "SO FAR SO GOOD|Things are going well so far",
    "SPEAK OF THE DEVIL|The person we were just talking about showed up",
    "THAT IS THE LAST STRAW|My patience has run out",
    "THE BEST OF BOTH WORLDS|An ideal situation",
    "TIME FLIES WHEN YOU ARE HAVING FUN|You don't notice how long it lasts",
    "TO GET BENT OUT OF SHAPE|To get upset",
    "TO MAKE MATTERS WORSE|Make a problem worse",
    "UNDER THE WEATHER|Sick",
    "WE WILL CROSS THAT BRIDGE WHEN WE COME TO IT|Let's not talk about that problem right now",
    "WRAP YOUR HEAD AROUND SOMETHING|Understand something complicated",
    "YOU CAN SAY THAT AGAIN|That's true I agree",
    "YOUR GUESS IS AS GOOD AS MINE|I have no idea",
    "A BIRD IN THE HAND IS WORTH TWO IN THE BUSH|What you have is worth more than what you might have later",
    "A PENNY FOR YOUR THOUGHTS|Tell me what you're thinking",
    "A PENNY SAVED IS A PENNY EARNED|Money you save today you can spend later",
    "A PERFECT STORM|The worst possible situation",
    "ACTIONS SPEAK LOUDER THAN WORDS|Believe what people do and not what they say",
    "ADD INSULT TO INJURY|To make a bad situation worse",
    "BARKING UP THE WRONG TREE|To be mistaken to be looking for solutions in the wrong place",
    "BIRDS OF A FEATHER FLOCK TOGETHER|People who are alike are often friends",
    "BITE OFF MORE THAN YOU CAN CHEW|Take on a project that you cannot finish",
    "BREAK THE ICE|Make people feel more comfortable",
    "BY THE SKIN OF YOUR TEETH|Just barely",
    "COMPARE APPLES TO ORANGES|Comparing two things that cannot be compared",
    "COSTS AN ARM AND A LEG|Very expensive",
    "DO SOMETHING AT THE DROP OF A HAT|Do something without having planned beforehand",
    "DO UNTO OTHERS AS YOU WOULD HAVE THEM DO UNTO YOU|Treat people fairly",
    "DON'T CRY OVER SPILT MILK|There's no reason to complain about something that can't be fixed",
    "DON'T PUT ALL YOUR EGGS IN ONE BASKET|What you're doing is too risky",
    "EVERY CLOUD HAS A SILVER LINING|Good things come after bad things",
    "GET A TASTE OF YOUR OWN MEDICINE|Get treated the way you've been treating others",
    "HEAR SOMETHING STRAIGHT FROM THE HORSE'S MOUTH|Hear something from the person involved",
    "HIT THE NAIL ON THE HEAD|Get something exactly right",
    "IGNORANCE IS BLISS|You're better off not knowing",
    "IT TAKES TWO TO TANGO|One person alone isn't responsible",
    "JUMP ON THE BANDWAGON|Follow a trend do what everyone else is doing",
    "KEEP YOUR CHIN UP|Be quiet",
    "KILL TWO BIRDS WITH ONE STONE|Get two things done with a single action",
    "LEAVE NO STONE UNTURNED|Look everywhere",
    "LET SLEEPING DOGS LIE|Stop discussing an issue",
    "LET THE CAT OUT OF THE BAG|Give away a secret",
    "LOOK BEFORE YOU LEAP|Take only calculated risks",
    "ONCE IN A BLUE MOON|Rarely",
    "PIECE OF CAKE|A task that can be accomplished very easily",
    "PLAY DEVIL'S ADVOCATE|To argue the opposite just for the sake of argument",
    "PUT SOMETHING ON ICE|Put a project on hold",
    "RAIN ON SOMEONE'S PARADE|To spoil something",
    "SAVING FOR A RAINY DAY|Saving money for later",
    "SLOW AND STEADY WINS THE RACE|Reliability is more important than speed",
    "SPILL THE BEANS|Give away a secret",
    "TAKE A RAIN CHECK|Postpone a plan",
    "TAKE IT WITH A GRAIN OF SALT|Don’t take it too seriously",
    "THE BALL IS IN YOUR COURT|It's your decision",
    "THE BEST THING SINCE SLICED BREAD|A really great invention",
    "THE DEVIL IS IN THE DETAILS|It looks good from a distance but when you look closer there are problems",
    "THE EARLY BIRD GETS THE WORM|The first people get the best stuff",
    "THE ELEPHANT IN THE ROOM|The big issue the problem people are avoiding",
    "THE WHOLE NINE YARDS|Everything All of it",
    "THERE ARE OTHER FISH IN THE SEA|It's ok to miss this opportunity Others will arise",
    "THERE'S A METHOD TO HIS MADNESS|He seems crazy but actually he's clever",
    "THERE'S NO SUCH THING AS A FREE LUNCH|Nothing is entirely free",
    "THROW CAUTION TO THE WIND|Take a risk",
    "YOU CAN'T JUDGE A BOOK BY ITS COVER|This person or thing may look bad but it's good inside",
    
    // Video Games
    "HALF LIFE|Gordon Freeman's adventure",
    "PORTAL|The cake is a lie",
    "MASS EFFECT|Commander Shepard saves the galaxy",
    "SKYRIM|Fus Ro Dah!",
    "FALLOUT|War war never changes",
    "DARK SOULS|Prepare to die",
    "BLOODBORNE|Fear the old blood",
    "THE LAST OF US|Joel and Ellie's journey",
    "UNCHARTED|Nathan Drake's treasure hunting",
    "GOD OF WAR|Kratos and Atreus",
    "HORIZON ZERO DAWN|Aloy fights robotic dinosaurs",
    "GHOST OF TSUSHIMA|Jin Sakai the samurai",
    "SPIDER MAN|Peter Parker swinging through New York",
    "SUPER SMASH BROS|Nintendo characters fighting each other",
    "MARIO KART|Racing game that ruins friendships",
    "THE LEGEND OF ZELDA OCARINA OF TIME|Classic N64 adventure",
    "BREATH OF THE WILD|Open world Hyrule",
    "TEARS OF THE KINGDOM|Sequel to Breath of the Wild",
    "ANIMAL CROSSING NEW HORIZONS|Deserted island getaway",
    "SPLATOON|Squid kids painting turf",
    "STREET FIGHTER|Ryu and Ken's fighting game",
    "MORTAL KOMBAT|Fatality!",
    "TEKKEN|The King of Iron Fist Tournament",
    "TOMB RAIDER|Lara Croft explores ruins",
    "ASSASSINS CREED|Nothing is true everything is permitted",
    "FAR CRY|Madness and survival in exotic locations",
    "BIOSHOCK|Would you kindly?",
    "BORDERLANDS|Vault hunters on Pandora",
    "DESTINY|Guardians protecting the Last City",
    "WARFRAME|Space ninjas playing for free",
    "WORLD OF WARCRAFT|For the Horde! For the Alliance!",
    "DIABLO|Hack and slash in Sanctuary",
    "STARCRAFT|Zerg rush",
    "DOTA TWO|Defense of the Ancients",
    "LEAGUE OF LEGENDS|Summoner's Rift MOBA",
    "COUNTER STRIKE|Terrorists win",
    "VALORANT|Riot's tactical hero shooter",
    "OVERWATCH|Heroes never die",
    "TEAM FORTRESS TWO|Hats and payload carts",
    "ROCKET LEAGUE|Car soccer",
    "FALL GUYS|Bean obstacle course",
    "AMONG US|There is an impostor among us",
    "FIVE NIGHTS AT FREDDYS|Terrifying animatronics",
    "UNDERTALE|You are filled with determination",
    "HOLLOW KNIGHT|Bug adventure in Hallownest",
    "CELESTE|Climbing a mountain platformer",
    "HADES|Escaping the Greek underworld",
    "STARDEW VALLEY|Farming life simulation",
    "TERRARIA|Two-dimensional Minecraft alternative",
    "DON'T STARVE|Survival in the constant",
    "SUBNAUTICA|Terror in the ocean depths",
    
    // Movies & Pop Culture
    "THE SHAWSHANK REDEMPTION|Andy Dufresne escapes prison",
    "THE GODFATHER|The Corleone family",
    "THE DARK KNIGHT|Batman faces the Joker",
    "THE LORD OF THE RINGS|Frodo's journey to Mount Doom",
    "PULP FICTION|Vincent Vega and Jules Winnfield",
    "FORREST GUMP|Life is like a box of chocolates",
    "FIGHT CLUB|First rule is you do not talk about it",
    "INCEPTION|Dreams within dreams",
    "STAR WARS THE EMPIRE STRIKES BACK|I am your father",
    "THE MATRIX|Neo takes the red pill",
    "GOODFELLAS|As far back as I can remember I always wanted to be a gangster",
    "SEVEN SAMURAI|Akira Kurosawa's masterpiece",
    "CITY OF GOD|Life in the favelas of Rio",
    "THE SILENCE OF THE LAMBS|Clarice Starling and Hannibal Lecter",
    "ITS A WONDERFUL LIFE|George Bailey discovers his worth",
    "SPIRITED AWAY|Chihiro's magical adventure",
    "SAVING PRIVATE RYAN|WWII Normandy invasion",
    "THE GREEN MILE|John Coffey's miracles",
    "INTERSTELLAR|Cooper travels through a wormhole",
    "PARASITE|The Kim family infiltrates a wealthy household",
    "THE LION KING|Simba reclaims the Pride Lands",
    "GLADIATOR|Maximus seeks vengeance",
    "THE PRESTIGE|Two rival magicians",
    "THE DEPARTED|Cops and mobsters in Boston",
    "WHIPLASH|Not quite my tempo",
    "THE TRUMAN SHOW|His whole life is a TV show",
    "JURASSIC PARK|Welcome to... dinosaur island",
    "BACK TO THE FUTURE|Marty McFly and Doc Brown",
    "THE TERMINATOR|I'll be back",
    "ALIEN|In space no one can hear you scream",
    "AVENGERS ENDGAME|I am Iron Man",
    "BLACK PANTHER|Wakanda Forever",
    "SPIDER MAN INTO THE SPIDER VERSE|Miles Morales becomes a hero",
    "TOY STORY|Woody and Buzz",
    "FINDING NEMO|Marlin searches for his son",
    "THE INCREDIBLES|A family of superheroes",
    "UP|Carl ties balloons to his house",
    "WALL E|A lonely robot cleans Earth",
    "INSIDE OUT|Joy Sadness Anger Fear and Disgust",
    "COCO|Miguel visits the Land of the Dead",
    
    // Geography / Landmarks
    "THE GREAT SPHINX|Lion body human head in Egypt",
    "TAJ MAHAL|White marble mausoleum in India",
    "MOUNT KILIMANJARO|Highest mountain in Africa",
    "THE SAHARA DESERT|Largest hot desert in the world",
    "THE AMAZON RAINFOREST|The lungs of the Earth",
    "THE GREAT BARRIER REEF|Coral system off the coast of Australia",
    "ANGKOR WAT|Temple complex in Cambodia",
    "PETRA|The Rose City in Jordan",
    "CHICHEN ITZA|Mayan ruins in Mexico",
    "MOUNT VESUVIUS|Volcano that destroyed Pompeii",
    "THE ALHAMBRA|Moorish palace in Spain",
    "BIG BEN|Famous clock tower in London",
    "THE KREMLIN|Fortified complex in Moscow",
    "SYDNEY HARBOUR BRIDGE|Iconic Australian bridge",
    "MOUNT RUSHMORE|Presidents carved into a mountain",
    "YELLOWSTONE NATIONAL PARK|Home to Old Faithful",
    "YOSEMITE NATIONAL PARK|Famous for El Capitan and Half Dome",
    "THE EVERGLADES|Tropical wetlands in Florida",
    "THE DEAD SEA|Salt lake bordering Jordan and Israel",
    "THE GALAPAGOS ISLANDS|Where Darwin studied evolution"
];

// Format: "Quote|Movie"
const rawQuotes = [
    // AFI Top 100 + Popular
    "Frankly, my dear, I don't give a damn.|Gone with the Wind",
    "I'm going to make him an offer he can't refuse.|The Godfather",
    "You don't understand! I coulda had class. I coulda been a contender. I could've been somebody, instead of a bum, which is what I am.|On the Waterfront",
    "Toto, I've a feeling we're not in Kansas anymore.|The Wizard of Oz",
    "Here's looking at you, kid.|Casablanca",
    "Go ahead, make my day.|Sudden Impact",
    "All right, Mr. DeMille, I'm ready for my close-up.|Sunset Boulevard",
    "May the Force be with you.|Star Wars",
    "Fasten your seatbelts. It's going to be a bumpy night.|All About Eve",
    "You talkin' to me?|Taxi Driver",
    "What we've got here is failure to communicate.|Cool Hand Luke",
    "I love the smell of napalm in the morning.|Apocalypse Now",
    "Love means never having to say you're sorry.|Love Story",
    "The stuff that dreams are made of.|The Maltese Falcon",
    "E.T. phone home.|E.T. the Extra-Terrestrial",
    "They call me Mister Tibbs!|In the Heat of the Night",
    "Rosebud.|Citizen Kane",
    "Made it, Ma! Top of the world!|White Heat",
    "I'm as mad as hell, and I'm not going to take this anymore!|Network",
    "Louis, I think this is the beginning of a beautiful friendship.|Casablanca",
    "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.|The Silence of the Lambs",
    "Bond. James Bond.|Dr. No",
    "There's no place like home.|The Wizard of Oz",
    "I am big! It's the pictures that got small.|Sunset Boulevard",
    "Show me the money!|Jerry Maguire",
    "Why don't you come up sometime and see me?|She Done Him Wrong",
    "I'm walking here! I'm walking here!|Midnight Cowboy",
    "Play it, Sam. Play 'As Time Goes By.'|Casablanca",
    "You can't handle the truth!|A Few Good Men",
    "I want to be alone.|Grand Hotel",
    "After all, tomorrow is another day!|Gone with the Wind",
    "Round up the usual suspects.|Casablanca",
    "I'll have what she's having.|When Harry Met Sally...",
    "You know how to whistle, don't you, Steve? You just put your lips together and blow.|To Have and Have Not",
    "You're gonna need a bigger boat.|Jaws",
    "Badges? We ain't got no badges! We don't need no badges! I don't have to show you any stinking badges!|The Treasure of the Sierra Madre",
    "I'll be back.|The Terminator",
    "Today, I consider myself the luckiest man on the face of the earth.|The Pride of the Yankees",
    "If you build it, he will come.|Field of Dreams",
    "Mama always said life was like a box of chocolates. You never know what you're gonna get.|Forrest Gump",
    "We rob banks.|Bonnie and Clyde",
    "Plastics.|The Graduate",
    "We'll always have Paris.|Casablanca",
    "I see dead people.|The Sixth Sense",
    "Stella! Hey, Stella!|A Streetcar Named Desire",
    "Oh, Jerry, don't let's ask for the moon. We have the stars.|Now, Voyager",
    "Shane. Shane. Come back!|Shane",
    "Well, nobody's perfect.|Some Like It Hot",
    "It's alive! It's alive!|Frankenstein",
    "Houston, we have a problem.|Apollo 13",
    "You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?|Dirty Harry",
    "You had me at 'hello.'|Jerry Maguire",
    "There's no crying in baseball!|A League of Their Own",
    "La-dee-da, la-dee-da.|Annie Hall",
    "A boy's best friend is his mother.|Psycho",
    "Greed, for lack of a better word, is good.|Wall Street",
    "Keep your friends close, but your enemies closer.|The Godfather Part II",
    "As God is my witness, I'll never be hungry again.|Gone with the Wind",
    "Well, here's another nice mess you've gotten me into!|Sons of the Desert",
    "Say 'hello' to my little friend!|Scarface",
    "What a dump.|Beyond the Forest",
    "Mrs. Robinson, you're trying to seduce me. Aren't you?|The Graduate",
    "Gentlemen, you can't fight in here! This is the War Room!|Dr. Strangelove",
    "Elementary, my dear Watson.|The Adventures of Sherlock Holmes",
    "Take your stinking paws off me, you damned dirty ape.|Planet of the Apes",
    "Of all the gin joints in all the towns in all the world, she walks into mine.|Casablanca",
    "Here's Johnny!|The Shining",
    "They're here!|Poltergeist",
    "Is it safe?|Marathon Man",
    "Wait a minute, wait a minute. You ain't heard nothin' yet!|The Jazz Singer",
    "No wire hangers, ever!|Mommie Dearest",
    "Mother of mercy, is this the end of Rico?|Little Caesar",
    "Forget it, Jake, it's Chinatown.|Chinatown",
    "I have always depended on the kindness of strangers.|A Streetcar Named Desire",
    "Hasta la vista, baby.|Terminator 2: Judgment Day",
    "Soylent Green is people!|Soylent Green",
    "Open the pod bay doors, HAL.|2001: A Space Odyssey",
    "Striker: Surely you can't be serious. Rumack: I am serious...and don't call me Shirley.|Airplane!",
    "Yo, Adrian!|Rocky",
    "Hello, gorgeous.|Funny Girl",
    "Toga! Toga!|National Lampoon's Animal House",
    "Listen to them. Children of the night. What music they make.|Dracula",
    "Oh, no, it wasn't the airplanes. It was Beauty killed the Beast.|King Kong",
    "My precious.|The Lord of the Rings: The Two Towers",
    "Attica! Attica!|Dog Day Afternoon",
    "Sawyer, you're going out a youngster, but you've got to come back a star!|42nd Street",
    "Listen to me, mister. You're my knight in shining armor. Don't you forget it. You're going to get back on that horse, and I'm going to be right behind you, holding on tight, and away we're gonna go, go, go!|On Golden Pond",
    "Tell 'em to go out there with all they got and win just one for the Gipper.|Knute Rockne, All American",
    "A martini. Shaken, not stirred.|Goldfinger",
    "Who's on first?|The Naughty Nineties",
    "Cinderella story. Outta nowhere. A former greenskeeper, now, about to become the Masters champion. It looks like a mirac...It's in the hole! It's in the hole! It's in the hole!|Caddyshack",
    "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.|Ferris Bueller's Day Off",
    "Carpe diem. Seize the day, boys. Make your lives extraordinary.|Dead Poets Society",
    "My mama always said, 'Stupid is as stupid does.'|Forrest Gump",
    "I'm the king of the world!|Titanic",
    
    // Modern / Nerd / Geek Culture
    "To infinity and beyond!|Toy Story",
    "I am Iron Man.|Iron Man",
    "Avengers, assemble.|Avengers: Endgame",
    "Wakanda Forever!|Black Panther",
    "I am your father.|Star Wars: The Empire Strikes Back",
    "Do, or do not. There is no try.|Star Wars: The Empire Strikes Back",
    "I'm Mary Poppins, y'all!|Guardians of the Galaxy Vol. 2",
    "That's my secret, Captain: I'm always angry.|The Avengers",
    "Why so serious?|The Dark Knight",
    "You either die a hero, or you live long enough to see yourself become the villain.|The Dark Knight",
    "With great power comes great responsibility.|Spider-Man",
    "It's not who I am underneath, but what I do that defines me.|Batman Begins",
    "Are you not entertained?|Gladiator",
    "I volunteer! I volunteer as tribute!|The Hunger Games",
    "The first rule of Fight Club is: You do not talk about Fight Club.|Fight Club",
    "There is no spoon.|The Matrix",
    "I know kung fu.|The Matrix",
    "You take the blue pill, the story ends. You wake up in your bed and believe whatever you want to believe. You take the red pill, you stay in Wonderland, and I show you how deep the rabbit hole goes.|The Matrix",
    "Just keep swimming.|Finding Nemo",
    "Roads? Where we're going we don't need roads.|Back to the Future",
    "Great Scott!|Back to the Future",
    "Nobody puts Baby in a corner.|Dirty Dancing",
    "Every time a bell rings, an angel gets his wings.|It's a Wonderful Life",
    "They may take our lives, but they'll never take our freedom!|Braveheart",
    "I feel the need - the need for speed!|Top Gun",
    "You're a wizard, Harry.|Harry Potter and the Sorcerer's Stone",
    "I solemnly swear that I am up to no good.|Harry Potter and the Prisoner of Azkaban",
    "It does not do to dwell on dreams and forget to live.|Harry Potter and the Sorcerer's Stone",
    "I am Groot.|Guardians of the Galaxy",
    "I love you 3000.|Avengers: Endgame",
    "As if!|Clueless",
    "You sit on a throne of lies.|Elf",
    "I'm in a glass case of emotion!|Anchorman",
    "60 percent of the time, it works every time.|Anchorman",
    "By Grabthar's hammer, by the suns of Worvan, you shall be avenged.|Galaxy Quest",
    "Never give up, never surrender!|Galaxy Quest",
    "You shall not pass!|The Lord of the Rings: The Fellowship of the Ring",
    "Even the smallest person can change the course of the future.|The Lord of the Rings: The Fellowship of the Ring",
    "I'm not a regular mom, I'm a cool mom.|Mean Girls",
    "That is so fetch.|Mean Girls",
    "On Wednesdays we wear pink.|Mean Girls",
    "Get in loser, we're going shopping.|Mean Girls",
    "Some people are worth melting for.|Frozen",
    "Let it go!|Frozen",
    "Hakuna Matata.|The Lion King",
    "Oh yes, the past can hurt. But you can either run from it, or learn from it.|The Lion King",
    "Adventure is out there!|Up",
    "I am speed.|Cars",
    "Magic Mirror on the wall, who is the fairest one of all?|Snow White and the Seven Dwarfs",
    "If you ain't first, you're last.|Talladega Nights",
    "I'm not superstitious, but I am a little stitious.|The Office (TV)", // Okay it's TV but great quote
    "Pivot!|Friends (TV)", // TV
    "Bazinga!|The Big Bang Theory (TV)", // TV
    "Winter is coming.|Game of Thrones (TV)", // TV
    "You know nothing, Jon Snow.|Game of Thrones (TV)", // TV
    "Live long and prosper.|Star Trek",
    "Beam me up, Scotty.|Star Trek"
];

async function seedMassiveData() {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log("Connected to MongoDB for Massive Seed...");

        console.log(`Preparing to insert ${rawPhrases.length} phrases and ${rawQuotes.length} quotes...`);

        let newPhrases = 0;
        for (const raw of rawPhrases) {
            const [phrase, clue] = raw.split('|');
            const res = await Phrase.updateOne({ phrase }, { phrase, clue }, { upsert: true });
            if (res.upsertedCount > 0) newPhrases++;
        }

        let newQuotes = 0;
        for (const raw of rawQuotes) {
            const [quote, movie] = raw.split('|');
            const res = await MovieQuote.updateOne({ quote }, { quote, movie }, { upsert: true });
            if (res.upsertedCount > 0) newQuotes++;
        }

        const totalPhrases = await Phrase.countDocuments();
        const totalQuotes = await MovieQuote.countDocuments();

        console.log(`Massive Seed Complete!
Added Phrases: ${newPhrases} (Total: ${totalPhrases})
Added Quotes: ${newQuotes} (Total: ${totalQuotes})`);

    } catch (err) {
        console.error("Seed error:", err);
    } finally {
        mongoose.connection.close();
        process.exit(0);
    }
}

seedMassiveData();
