'use strict';

const { Word } = require('../models');

/** Embedded fallback when Mongo has no `Word` rows with `definition` set (same entries as seed). */
const SPELLING_BEE_WORDS = [
    { word: 'bicycle', def: 'A two-wheeled vehicle you pedal' },
    { word: 'mystery', def: 'Something unknown or hard to explain' },
    { word: 'courage', def: 'Bravery in the face of fear' },
    { word: 'galaxy', def: 'A huge system of stars' },
    { word: 'journey', def: 'A long trip from one place to another' },
    { word: 'puzzle', def: 'A game or problem that tests cleverness' },
    { word: 'whisper', def: 'To speak very quietly' },
    { word: 'diamond', def: 'A hard, shiny precious stone' },
    { word: 'freedom', def: 'The power to act or speak without restraint' },
    { word: 'harvest', def: 'The season or act of gathering crops' },
    { word: 'island', def: 'Land surrounded by water' },
    { word: 'jungle', def: 'A dense tropical forest' },
    { word: 'kitchen', def: 'Room where food is cooked' },
    { word: 'lantern', def: 'A portable light, often with a case' },
    { word: 'melody', def: 'A sequence of musical notes' },
    { word: 'nectar', def: 'Sweet liquid in flowers; bees love it' },
    { word: 'ocean', def: 'A huge body of salt water' },
    { word: 'palace', def: 'A large, splendid house for royalty' },
    { word: 'quiver', def: 'To shake slightly; or a case for arrows' },
    { word: 'rainbow', def: 'A colored arc in the sky after rain' },
    { word: 'sapphire', def: 'A deep blue precious stone' },
    { word: 'treasure', def: 'Valuables like gold or gems' },
    { word: 'umbrella', def: 'A device that shields you from rain' },
    { word: 'village', def: 'A small community of houses' },
    { word: 'wisdom', def: 'Deep knowledge and good judgment' },
    { word: 'oxygen', def: 'Gas we breathe to stay alive' },
    { word: 'pyramid', def: 'A triangular ancient monument' },
    { word: 'quartz', def: 'A hard mineral used in watches' },
    { word: 'radar', def: 'System that detects objects with radio waves' },
    { word: 'skeleton', def: 'The bones inside a body' },
    { word: 'tornado', def: 'A violent spinning column of wind' },
    { word: 'unicorn', def: 'A mythical horse with one horn' },
    { word: 'volcano', def: 'A mountain that can erupt lava' },
    { word: 'wizard', def: 'A person thought to use magic' },
    { word: 'xylophone', def: 'A musical instrument with wooden bars' },
    { word: 'yogurt', def: 'A thick, creamy dairy food' },
    { word: 'zephyr', def: 'A soft, gentle breeze' },
    { word: 'ancient', def: 'Very old, from long ago' },
    { word: 'brilliant', def: 'Very bright or very smart' },
    { word: 'chocolate', def: 'A sweet brown treat from cacao' },
    { word: 'dinosaur', def: 'An extinct reptile from prehistory' },
    { word: 'echo', def: 'A sound that repeats after bouncing back' },
    { word: 'festival', def: 'A celebration with events and crowds' },
    { word: 'giraffe', def: 'A tall African animal with a long neck' },
    { word: 'horizon', def: 'The line where earth meets the sky' },
    { word: 'igloo', def: 'A dome-shaped snow shelter' },
    { word: 'jacket', def: 'A short coat worn on top' },
    { word: 'kangaroo', def: 'An Australian hopping marsupial' },
    { word: 'lemon', def: 'A sour yellow citrus fruit' },
    { word: 'mountain', def: 'A very high natural rise of land' },
    { word: 'narwhal', def: 'An Arctic whale with a long tusk' },
    { word: 'octopus', def: 'A sea creature with eight arms' },
    { word: 'penguin', def: 'A flightless black-and-white bird of cold seas' },
    { word: 'quicksand', def: 'Wet sand that pulls things down' },
    { word: 'rocket', def: 'A vehicle that flies to space' },
    { word: 'satellite', def: 'An object orbiting a planet' },
    { word: 'tunnel', def: 'A passage dug through a hill or under water' },
    { word: 'vulture', def: 'A bird that feeds on carrion' },
    { word: 'walrus', def: 'A large tusked Arctic sea mammal' },
    { word: 'yesterday', def: 'The day before today' },
    { word: 'zenith', def: 'The highest point overhead in the sky' },
    { word: 'abundant', def: 'Existing in large quantities' },
    { word: 'accordion', def: 'A box-shaped musical instrument with keys and bellows' },
    { word: 'adventure', def: 'An exciting or unusual experience' },
    { word: 'alligator', def: 'A large reptile similar to a crocodile' },
    { word: 'ambition', def: 'A strong desire to achieve something' },
    { word: 'anaconda', def: 'A very large South American snake' },
    { word: 'antenna', def: 'A rod or wire that sends or receives signals' },
    { word: 'applause', def: 'Clapping to show approval' },
    { word: 'aquarium', def: 'A tank where fish and water animals live' },
    { word: 'architect', def: 'Someone who designs buildings' },
    { word: 'asteroid', def: 'A rocky object orbiting the sun' },
    { word: 'avalanche', def: 'A mass of snow sliding down a mountain' },
    { word: 'backpack', def: 'A bag carried on your back' },
    { word: 'balloon', def: 'A thin rubber bag filled with air or gas' },
    { word: 'banana', def: 'A long yellow tropical fruit' },
    { word: 'barbecue', def: 'Outdoor cooking over a grill' },
    { word: 'basement', def: 'The lowest floor of a building, often underground' },
    { word: 'battery', def: 'A device that stores electrical energy' },
    { word: 'beaver', def: 'A rodent that builds dams' },
    { word: 'blizzard', def: 'A severe snowstorm with strong wind' },
    { word: 'blueprint', def: 'A detailed plan for building something' },
    { word: 'bonfire', def: 'A large outdoor fire' },
    { word: 'bouquet', def: 'A bunch of flowers' },
    { word: 'broccoli', def: 'A green vegetable like tiny trees' },
    { word: 'buffalo', def: 'A large wild ox or bison' },
    { word: 'bungalow', def: 'A small house with a single story' },
    { word: 'butterfly', def: 'An insect with large colorful wings' },
    { word: 'cactus', def: 'A spiny desert plant' },
    { word: 'calculator', def: 'A device that does math' },
    { word: 'calendar', def: 'A chart showing days and months' },
    { word: 'canyon', def: 'A deep valley with steep sides' },
    { word: 'carousel', def: 'A rotating platform with seats, often horses' },
    { word: 'casserole', def: 'A baked dish of meat, vegetables, or pasta' },
    { word: 'cathedral', def: 'A large important Christian church' },
    { word: 'celery', def: 'A crunchy green stalk vegetable' },
    { word: 'cemetery', def: 'A place where dead people are buried' },
    { word: 'century', def: 'A period of one hundred years' },
    { word: 'chameleon', def: 'A lizard that changes color' },
    { word: 'cheetah', def: 'The fastest land animal, a spotted cat' },
    { word: 'chimney', def: 'A pipe above a fireplace for smoke' },
    { word: 'cinnamon', def: 'A sweet brown spice from tree bark' },
    { word: 'clarinet', def: 'A woodwind instrument with a reed' },
    { word: 'clipboard', def: 'A flat board with a clip for papers' },
    { word: 'coconut', def: 'A large tropical fruit with milk inside' },
    { word: 'companion', def: 'A friend who spends time with you' },
    { word: 'computer', def: 'An electronic machine that processes data' },
    { word: 'confetti', def: 'Tiny pieces of colored paper thrown at parties' },
    { word: 'cucumber', def: 'A long green salad vegetable' },
    { word: 'curtain', def: 'Cloth that covers a window or stage' },
    { word: 'cylinder', def: 'A solid tube shape with circles at each end' },
    { word: 'dandelion', def: 'A yellow wildflower with fluffy seeds' },
    { word: 'dictionary', def: 'A book listing words and their meanings' },
    { word: 'dolphin', def: 'A smart sea mammal that jumps in water' },
    { word: 'dragonfly', def: 'An insect with long wings that skims water' },
    { word: 'drought', def: 'A long period with little or no rain' },
    { word: 'dungeon', def: 'An underground prison in old castles' },
    { word: 'eagle', def: 'A large bird of prey with sharp vision' },
    { word: 'earthquake', def: 'Shaking of the ground from tectonic movement' },
    { word: 'eclipse', def: 'When one heavenly body blocks light from another' },
    { word: 'electricity', def: 'A form of energy that powers lights and machines' },
    { word: 'elephant', def: 'A huge animal with a trunk and tusks' },
    { word: 'elevator', def: 'A platform that moves people between floors' },
    { word: 'emerald', def: 'A bright green precious stone' },
    { word: 'emperor', def: 'The ruler of an empire' },
    { word: 'envelope', def: 'A paper container for a letter' },
    { word: 'evergreen', def: 'A tree that keeps its leaves all year' },
    { word: 'exercise', def: 'Physical activity to stay healthy' },
    { word: 'explorer', def: 'Someone who travels to discover new places' },
    { word: 'falcon', def: 'A fast bird of prey' },
    { word: 'feather', def: 'A light structure covering a bird' },
    { word: 'firefly', def: 'A beetle that glows in the dark' },
    { word: 'flamingo', def: 'A tall pink wading bird' },
    { word: 'flannel', def: 'A soft warm cloth for shirts or blankets' },
    { word: 'florist', def: 'Someone who sells and arranges flowers' },
    { word: 'footprint', def: 'A mark left by a foot on the ground' },
    { word: 'forehead', def: 'The part of the face above the eyes' },
    { word: 'fossil', def: 'Preserved remains of ancient plants or animals' },
    { word: 'fountain', def: 'A jet or spray of water for decoration' },
    { word: 'freckle', def: 'A small brown spot on skin' },
    { word: 'fuchsia', def: 'A shrub with drooping pink or purple flowers' },
    { word: 'furniture', def: 'Tables, chairs, and beds in a home' },
    { word: 'gargoyle', def: 'A carved monster spout on old buildings' },
    { word: 'gazelle', def: 'A slender fast African antelope' },
    { word: 'geography', def: 'The study of Earth’s lands and peoples' },
    { word: 'gerbil', def: 'A small desert rodent often kept as a pet' },
    { word: 'glacier', def: 'A slow-moving river of ice' },
    { word: 'goblin', def: 'A mischievous creature in folklore' },
    { word: 'gorilla', def: 'The largest ape, from African forests' },
    { word: 'gravity', def: 'The force that pulls objects toward Earth' },
    { word: 'grenade', def: 'A small thrown bomb' },
    { word: 'guitar', def: 'A stringed instrument you strum' },
    { word: 'hamster', def: 'A small furry pet with cheek pouches' },
    { word: 'hangar', def: 'A large building where aircraft are kept' },
    { word: 'harmonica', def: 'A small mouth organ with metal reeds' },
    { word: 'hedgehog', def: 'A spiny insect-eating mammal' },
    { word: 'helicopter', def: 'An aircraft with spinning overhead blades' },
    { word: 'hibernate', def: 'To sleep through winter like a bear' },
    { word: 'hickory', def: 'A North American tree with hard wood' },
    { word: 'hospital', def: 'A place where sick people are treated' },
    { word: 'hummingbird', def: 'A tiny bird that hovers at flowers' },
    { word: 'hurricane', def: 'A powerful tropical storm' },
    { word: 'hyena', def: 'A doglike African scavenger' },
    { word: 'iceberg', def: 'A huge floating mass of ice' },
    { word: 'iguana', def: 'A large tropical lizard' },
    { word: 'imagine', def: 'To picture something in your mind' },
    { word: 'insect', def: 'A small six-legged creature like an ant or bee' },
    { word: 'isotope', def: 'A form of an element with different atomic mass' },
    { word: 'jalapeno', def: 'A hot green chili pepper' },
    { word: 'jellyfish', def: 'A soft stinging sea creature' },
    { word: 'journal', def: 'A daily record of events or a magazine' },
    { word: 'juggler', def: 'Someone who keeps objects moving in the air' },
    { word: 'kayak', def: 'A small narrow boat you paddle' },
    { word: 'ketchup', def: 'A thick red sauce for fries and burgers' },
    { word: 'kilometer', def: 'A metric unit equal to one thousand meters' },
    { word: 'kingfisher', def: 'A colorful bird that dives for fish' },
    { word: 'kitten', def: 'A young cat' },
    { word: 'koala', def: 'An Australian tree-dwelling marsupial' },
    { word: 'labyrinth', def: 'A complicated maze of paths' },
    { word: 'ladybug', def: 'A small round beetle, often red with spots' },
    { word: 'language', def: 'A system of spoken or written words' },
    { word: 'lavender', def: 'A fragrant purple herb' },
    { word: 'leopard', def: 'A large spotted wild cat' },
    { word: 'lighthouse', def: 'A tower with a bright beam for ships' },
    { word: 'limousine', def: 'A long luxury car' },
    { word: 'llama', def: 'A South American animal related to the camel' },
    { word: 'lobster', def: 'A large clawed sea shellfish' },
    { word: 'locust', def: 'A grasshopper that swarms and eats crops' },
    { word: 'luggage', def: 'Bags and suitcases for travel' },
    { word: 'macaroni', def: 'Tube-shaped pasta' },
    { word: 'magazine', def: 'A periodical publication' },
    { word: 'magnet', def: 'An object that attracts iron' },
    { word: 'mammoth', def: 'An extinct hairy elephant' },
    { word: 'manatee', def: 'A gentle plant-eating sea mammal' },
    { word: 'mandolin', def: 'A small stringed instrument like a lute' },
    { word: 'marathon', def: 'A long-distance running race' },
    { word: 'marshmallow', def: 'A soft sweet often toasted on a stick' },
    { word: 'mechanic', def: 'Someone who repairs machines' },
    { word: 'megaphone', def: 'A cone that makes your voice louder' },
    { word: 'meteor', def: 'A space rock that burns up entering the atmosphere' },
    { word: 'microscope', def: 'An instrument for seeing tiny things' },
    { word: 'moccasin', def: 'A soft shoe or a venomous snake' },
    { word: 'mongoose', def: 'A small fierce mammal that eats snakes' },
    { word: 'mosquito', def: 'A flying insect whose bite can itch' },
    { word: 'motorcycle', def: 'A two-wheeled motor vehicle' },
    { word: 'mushroom', def: 'A fungus with a cap and stem, some edible' },
    { word: 'nectarine', def: 'A smooth-skinned peach-like fruit' },
    { word: 'newspaper', def: 'Daily or weekly printed news' },
    { word: 'nightmare', def: 'A frightening dream' },
    { word: 'nostril', def: 'An opening of the nose for breathing' },
    { word: 'notebook', def: 'A book of blank pages for writing' },
    { word: 'novel', def: 'A long fictional story' },
    { word: 'nutmeg', def: 'A spice from a seed, used in baking' },
    { word: 'oatmeal', def: 'A hot breakfast food made from oats' },
    { word: 'octagon', def: 'A shape with eight sides' },
    { word: 'omelet', def: 'Eggs cooked flat and folded with filling' },
    { word: 'onion', def: 'A layered vegetable that can make you cry' },
    { word: 'opossum', def: 'A marsupial that may play dead' },
    { word: 'orchid', def: 'A flower with complex colorful blooms' },
    { word: 'ostrich', def: 'The largest bird, which cannot fly' },
    { word: 'otter', def: 'A playful furry river mammal' },
    { word: 'oyster', def: 'A shellfish that may contain a pearl' },
    { word: 'pajamas', def: 'Clothes worn for sleeping' },
    { word: 'panther', def: 'A large black or spotted wild cat' },
    { word: 'papaya', def: 'A tropical orange fruit with black seeds' },
    { word: 'parachute', def: 'A canopy used to slow a fall from the sky' },
    { word: 'parakeet', def: 'A small long-tailed pet bird' },
    { word: 'parrot', def: 'A colorful bird that can mimic speech' },
    { word: 'pastry', def: 'Flaky baked goods like croissants' },
    { word: 'peacock', def: 'A bird with a huge fan of tail feathers' },
    { word: 'pelican', def: 'A large bird with a pouch under its bill' },
    { word: 'pendulum', def: 'A swinging weight that keeps time' },
    { word: 'pepperoni', def: 'A spicy sausage on pizza' },
    { word: 'pheasant', def: 'A long-tailed game bird' },
    { word: 'photograph', def: 'A picture taken with a camera' },
    { word: 'pickle', def: 'A cucumber preserved in vinegar' },
    { word: 'pineapple', def: 'A tropical fruit with a spiky crown' },
    { word: 'platypus', def: 'An odd Australian mammal with a bill' },
    { word: 'porcupine', def: 'A rodent covered in sharp quills' },
    { word: 'porpoise', def: 'A small toothed whale related to dolphins' },
    { word: 'potato', def: 'A starchy underground vegetable' },
    { word: 'prairie', def: 'A wide area of flat grassland' },
    { word: 'pretzel', def: 'A twisted salty baked snack' },
    { word: 'pumpkin', def: 'A large orange squash carved at Halloween' },
    { word: 'python', def: 'A large nonvenomous constricting snake' },
    { word: 'quarantine', def: 'Isolation to stop disease spread' },
    { word: 'question', def: 'A sentence asked to get an answer' },
    { word: 'rabbit', def: 'A small hopping mammal with long ears' },
    { word: 'raccoon', def: 'A masked furry animal that raids trash' },
    { word: 'radiator', def: 'A heater for warming a room' },
    { word: 'rattlesnake', def: 'A venomous snake with a noisy tail' },
    { word: 'ravioli', def: 'Pasta squares filled with meat or cheese' },
    { word: 'reindeer', def: 'Arctic deer that pull Santa’s sleigh in stories' },
    { word: 'rhinoceros', def: 'A huge mammal with one or two horns' },
    { word: 'raspberry', def: 'A red berry made of many tiny druplets' },
    { word: 'restaurant', def: 'A place where meals are bought and eaten' },
    { word: 'rhubarb', def: 'A tart stalk used in pies' },
    { word: 'sandwich', def: 'Food between two slices of bread' },
    { word: 'saxophone', def: 'A brass woodwind with a curved metal body' },
    { word: 'scissors', def: 'A tool with two blades for cutting' },
    { word: 'scorpion', def: 'An arachnid with a venomous stinger tail' },
    { word: 'seahorse', def: 'A tiny fish with a horse-shaped head' },
    { word: 'seagull', def: 'A common gray and white coastal bird' },
    { word: 'seesaw', def: 'A plank balanced in the middle for two riders' },
    { word: 'sequoia', def: 'A giant California evergreen tree' },
    { word: 'sherbet', def: 'A frozen fruity dessert' },
    { word: 'skateboard', def: 'A board with wheels for tricks and riding' },
    { word: 'skunk', def: 'A black-and-white mammal with a bad smell' },
    { word: 'skyscraper', def: 'A very tall city building' },
    { word: 'sloth', def: 'A slow-moving tree mammal' },
    { word: 'snowflake', def: 'A crystal of frozen water from the sky' },
    { word: 'spaghetti', def: 'Long thin pasta with sauce' },
    { word: 'sparrow', def: 'A small common brown bird' },
    { word: 'spatula', def: 'A flat tool for flipping pancakes' },
    { word: 'spinach', def: 'A leafy green vegetable' },
    { word: 'squirrel', def: 'A bushy-tailed rodent that climbs trees' },
    { word: 'stethoscope', def: 'A doctor’s listening device for hearts and lungs' },
    { word: 'stingray', def: 'A flat sea fish with a whip-like tail' },
    { word: 'strawberry', def: 'A red berry with seeds on the outside' },
    { word: 'submarine', def: 'A vessel that travels underwater' },
    { word: 'sunflower', def: 'A tall plant with a large yellow bloom' },
    { word: 'surfboard', def: 'A board used to ride ocean waves' },
    { word: 'tambourine', def: 'A handheld drum with metal jingles' },
    { word: 'telescope', def: 'An instrument for seeing distant stars' },
    { word: 'thermometer', def: 'A device that measures temperature' },
    { word: 'thunder', def: 'The loud sound that follows lightning' },
    { word: 'tiger', def: 'A large orange-and-black striped wild cat' },
    { word: 'tomato', def: 'A red fruit often used as a vegetable' },
    { word: 'toucan', def: 'A tropical bird with a huge colorful bill' },
    { word: 'trampoline', def: 'A strong sheet for jumping high' },
    { word: 'triangle', def: 'A shape with three sides' },
    { word: 'trombone', def: 'A brass instrument with a sliding tube' },
    { word: 'tumbleweed', def: 'A dry plant that rolls in the wind' },
    { word: 'turbine', def: 'A machine driven by flowing fluid or gas' },
    { word: 'turtle', def: 'A reptile with a shell on its back' },
    { word: 'ukulele', def: 'A small four-stringed Hawaiian guitar' },
    { word: 'umbilical', def: 'Relating to the cord connecting a baby before birth' },
    { word: 'vacuum', def: 'A space with no air; or a cleaning machine' },
    { word: 'vegetable', def: 'An edible plant part like carrot or pea' },
    { word: 'velvet', def: 'A soft fabric with a short dense pile' },
    { word: 'violin', def: 'A small wooden string instrument played with a bow' },
    { word: 'violet', def: 'A small purple flower or the color' },
    { word: 'volleyball', def: 'A game of hitting a ball over a net' },
    { word: 'walnut', def: 'A tree nut with a hard shell' },
    { word: 'waterfall', def: 'A stream falling over a cliff' },
    { word: 'watermelon', def: 'A large green fruit with red sweet inside' },
    { word: 'weasel', def: 'A small slender furry predator' },
    { word: 'whistle', def: 'A high sound made by lips or a device' },
    { word: 'wildebeest', def: 'An African antelope that migrates in herds' },
    { word: 'wolverine', def: 'A stocky fierce mammal of northern forests' },
    { word: 'wombat', def: 'A burrowing Australian marsupial' },
    { word: 'woodpecker', def: 'A bird that drills holes in bark with its bill' },
    { word: 'wrestling', def: 'A sport of grappling and pinning an opponent' },
    { word: 'xenon', def: 'A heavy inert gas used in bright lamps' },
    { word: 'xerox', def: 'A brand often used to mean photocopy' },
    { word: 'yacht', def: 'A luxury boat for sailing or cruising' },
    { word: 'yellow', def: 'The color of a ripe banana' },
    { word: 'yodel', def: 'To sing with rapid changes between low and high pitch' },
    { word: 'yolk', def: 'The yellow center of an egg' },
    { word: 'zebra', def: 'An African wild horse with black and white stripes' },
    { word: 'zinnia', def: 'A bright garden flower' },
    { word: 'zucchini', def: 'A green summer squash' },
];

function shuffleCopy(arr) {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
}

async function fetchSpellingBeeFromDatabase() {
    const rows = await Word.find({
        definition: { $exists: true, $type: 'string', $regex: /\S/ },
    })
        .select('word definition')
        .lean();
    return rows.map((w) => ({
        word: String(w.word).toLowerCase(),
        def: w.definition,
    }));
}

/**
 * Prefer `Word` documents that have `definition` (seeded like Serverdle via `seed-expanded.js`).
 * Falls back to {@link SPELLING_BEE_WORDS} if the DB is empty or unreachable.
 */
async function buildRoundPool(rounds) {
    let pool;
    try {
        const fromDb = await fetchSpellingBeeFromDatabase();
        pool = fromDb.length > 0 ? fromDb : SPELLING_BEE_WORDS;
    } catch (e) {
        console.error('[spellingbee] Word load failed, using embedded list:', e.message);
        pool = SPELLING_BEE_WORDS;
    }
    const need = Math.min(rounds, pool.length);
    return shuffleCopy(pool).slice(0, need);
}

module.exports = { SPELLING_BEE_WORDS, buildRoundPool };
